apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-1175
  labels:
    deployment: docs-controller-deployment-1175
    docs-controller-deployment: "true"
spec:
  selector:
    matchLabels:
      deployment: docs-controller-deployment-1175
      docs-controller-deployment: "true"
  template:
    metadata:
      labels:
        deployment: docs-controller-deployment-1175
        docs-controller-deployment: "true"
    spec:
      initContainers:
      - name: git-clone
        image: gcr.io/priya-wadhwa/hugo@sha256:29a9ef0427218772b3d6a982feac3d855b1949cc78326ad1aeea8af32fa2ba38
        args: ["git", "clone", "https://github.com/priyawadhwa/skaffold-1.git", "--branch", "test-docs-site"]
        workingDir: "/empty"
        volumeMounts:
          - name: empty-vol
            mountPath: /empty
      containers:
      - name: server
        image: gcr.io/priya-wadhwa/hugo@sha256:29a9ef0427218772b3d6a982feac3d855b1949cc78326ad1aeea8af32fa2ba38
        args: ["hugo", "server", "--bind=0.0.0.0", "-D", "--baseURL=http://35.236.40.103:1313"]
        workingDir: "/empty/skaffold-1/docs"
        volumeMounts:
          - name: empty-vol
            mountPath: /empty
        ports:
        - containerPort: 1313
      volumes:
      - name: empty-vol
        emptyDir: {}
