apiVersion: apps/v1
kind: Deployment
metadata:
  name: docs-controller
  labels:
    run: docs
spec:
  selector:
    matchLabels:
      run: docs
  template:
    metadata:
      labels:
        run: docs
        docs-controller: true
    spec:
      serviceAccountName: admin-serviceaccount
      containers:
      - name: docs-controller
        image: gcr.io/k8s-skaffold/docs-controller:latest
        env:
        - name: GITHUB_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: github-token 
              key: token
        ports:
        - containerPort: 8080
