apiVersion: v1
kind: Service
metadata:
  name: docs4
  labels:
    deployment : docs-controller-deployment-4
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    deployment : docs-controller-deployment-4
    