apiVersion: v1
kind: Service
metadata:
  name: priya
  labels:
    priya: docs
spec:
  type: LoadBalancer
  ports:
  - port: 1313
    targetPort: 1313
    protocol: TCP
    name: http
  selector:
    priya: docs
    